# Site settings
title: "DongGyu Blog"
email: "kangkg0067@gmail.com"
description: "DongGyu's Dev Log: Journey of a Passionate Backend Developer"
author: "DongGyu Kang" 
baseurl: ""
url: "https://donggyu-kang.github.io"

# Social Profiles 
github_username: "donggyu-kang"
instagram_username: "don___gyu"

# Build settings
markdown: kramdown
highlighter: rouge # 코드 강조 기능
paginate: 5
paginate_path: "/posts/page:num/"

# Plugins
# 깃허브 페이지에서 기본적으로 지원하는 플러그인 목록
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap